- .gitignore
- mappings/community/D541487-convictions.json
- mappings/community/D814575-convictions.json
- mappings/community/D985513-convictions.json
- mappings/community/D991494-convictions.json
- mappings/community/DX12340A-convictions.json
- routes/view.js
- services/community-service.js
- tests/routes/view.test.js
- tests/services/community-service.test.js
As part of the work to populate some dev data that corresponds to test data in Delius I've updated the court-case-service endpoint that prepare-a-case is calling now that it has been implemented. 
The tests still all pass as I've updated the mocks as well but there will need to be some further fixes as there are some fields which differ between the mocks and what the court-case-service returns. I'll raise fixing this as [a separate story](https://dsdmoj.atlassian.net/browse/PIC-369).
> Fix probation-record to call correct endpoint

- routes/view.js
- tests/routes/view.test.js
Corrected issue where attendance data was being requested for inactive orders.
> PIC-416 Bugfix: Attendance data requested on inactive orders

- .circleci/config.yml
- Dockerfile
- README.md
- package-lock.json
- package.json
Updated builds to use Node.js LTS (Erbium) v12.18.0.
Updated development process to require Node.js LTS (Erbium) v12.18.0 or (Fermium) 14.4.0.
Updated README
Updated dependencies.
Removed Yarn version reference.
> Node security release

- Dockerfile
- package-lock.json
- package.json
Removed use of Yarn and change to use NPM
Corrected dependency for node-sass-middleware
Optimised production build in Dockerfile
> PIC-534 Prepare a Case - Dockerfile

- integration-tests/integration/common/common.spec.js
- integration-tests/integration/features/case-summary.feature
- integration-tests/integration/features/case-summary/case-summary.spec.js
- server/routes/index.js
- server/views/case-list.njk
- server/views/case-summary-record-order-breach.njk
- server/views/case-summary-record-order.njk
- server/views/case-summary-risk.njk
- server/views/case-summary.njk
- server/views/partials/case-details.njk
- tests/routes/view.test.js
- Added back to cases link on Case summary page that will take the user back to the case list they were viewing
- Noticed on the prototype that the page is no longer called 'Case details' but instead 'Case summary' - updated content to align with prototype.
- Updated `/details` endpoint to `/summary` with the UI now being referred to as 'Case summary'
- Added integration tests for back to cases link
- Ticket also mentions adding link to `Cases` to take the user to the latest case list but this has already been implemented.
> :lipstick: PIC-652: Added back to cases link

- integration-tests/integration/features/matching.feature
- integration-tests/integration/world/data/case-list/addedCasesList.js
- integration-tests/integration/world/data/case-list/fullFilteredList.js
- integration-tests/integration/world/data/case-list/probationStatusFilteredList.js
- mappings/case-list-full.json
- mappings/matching/default-detail.json
- server/routes/index.js
- server/views/case-list.njk
- server/views/case-summary.njk
- server/views/match-manual.njk
Includes CRN lookup and error message that was missed on PIC-647 (sorry)
Removed duplicate scenarios from BDD resulting from merge
Made 1st page of case list data more consistent with real data (no longer shows breach and SSO for defendants without a current order)
> BUGFIX - Possible records and probation status are displayed together

- server/views/case-list.njk
From a discussion with Charan earlier, we had discussed previously during testing that the "Recently added" and "Recently removed" tabs on the case list should be suppressed when there are no relevant cases.
This work is more urgent now as the matcher is no linger returning any "Recently removed" cases during the tactical release so I've completed this now to make sure the tab no longer shows, but will once we get to the strategic release and this data is then populated correctly.
> Suppress recently added and removed tabs when no relevant cases exist

- mappings/community/D541487-convictions.json
- mappings/community/D814575-convictions.json
- mappings/community/D985513-convictions.json
- mappings/community/D991494-convictions.json
- mappings/community/DX12340A-convictions.json
- package.json
- server/views/case-summary-record-order.njk
Following investigations with Alastair it has been decided to use sentence startDate instead of convictionDate, due to convictionDate displaying null for cases over 5 years old.
- Replaced convictionDate with sentence.startDate
- Updated mock data to reflect live sentence data
> :bug: PIC-726: fixed invalid date

- public/stylesheets/app/_key-details.scss
- server/views/case-summary-record-order.njk
- server/views/components/key-details-bar/template.njk
2 small changes following meeting with Charan and Alastair regarding PIC-679 (prototype front end alignment)
- suppress `pac-key-details-bar__bottom-block` if there's no probation status
- On view `case-summary-record-order` moved back link out of main content and into backLink block so displayed the same as other pages
> Pic 679 prototype alignment

- server/routes/index.js
Corrected issue causing the link confirmation message to not being displayed on offender summary screen
> Link confirmed message fix

- .circleci/config.yml
- README.md
- package-lock.json
- package.json
Updated README to reflect change of WireMock version
Updated govuk-frontend to 3.9.0
Updated swagger-client to 3.10.13
> Updated WireMock standalone to 2.27.2

- .circleci/config.yml
- Dockerfile
- README.md
- package.json
Project now requires the use of Node.js 12.18.4 or 14.11.0 which include important security updates.
> Updated Node.js versions to security releases

- helm_deploy/values-prod.yaml
Added the CIDR ranges which cover court users on DOM1 machines, accessing the service from an HMCTS Magistrates' Court network.
> :lock: Update IP whitelist to include HMCTS Magristrates' courts

- package-lock.json
- package.json
- server/routes/index.js
- server/utils/getBaseDateString.js
- server/views/case-list.njk
- tests/routes/view.test.js
:sparkles: Viewing case list on Sunday redirects to Monday
When viewing the case list on Sunday the application redirects to Monday.
In this case, the page title is changed from "Tomorrow" to "Monday DD MMMM".
Navigating back to case list from case summary functions correctly.
Unit tests include date mock to successfully test.
**N.B.** As this is a Node.js application we cannot mock the date for integration tests, therefore none are written and if the tests are run on a Sunday then we will have failing tests. There doesn't appear to be anything we can do about this.
> PIC-881 View Case List on Sunday

- mappings/community/D991494-breach-98765.json
- public/stylesheets/app/_white-space-format.scss
- public/stylesheets/app/all.scss
- server/views/case-summary-record-order-breach.njk
Used CSS styling for the white space formatting instead of `<pre>` tags as Cypress `.contains` excludes `<pre>` tags when ignoring invisible whitespaces.
See https://github.com/cypress-io/cypress/pull/5653 for more info
> :lipstick: PIC-917: Added whitespace formatting:

- .circleci/config.yml
I’ve removed the snyk image scan from the build process to allow the docker image to be pushed.
I’ve then added the image_scan to run in parallel with deploy_dev so that we can still be alerted.
> :construction_worker: Suppress snyk on build

- mappings/matching/3597035492-matches.json
- server/views/match-defendant.njk
- Small change, noticed in sprint planning that the matched defendant names were displaying with incorrect capitalisation as missing `properCase` nunjucks filter, so added that.
- Also updated the mock data to reflect real data
> :lipstick: PIC-990: Added properCase filter

- config.js
- integration-tests/integration/features/select-court.feature
- server/routes/index.js
- tests/routes/view.test.js
:adhesive_bandage: Strip trailing slash to make sure all links can be relative (and preserve any querystring)
:speech_balloon: Fixed incorrect court name
> BUGFIX Issue with relative links and change to court name

- server/views/case-list.njk
- server/views/components/days-navigation/template.njk
Day navigation was configured to use relative URLs but this causes an issue if you navigate to the **Recently added** or **Recently removed** tabs on the case list view.
I have implemented a _baseUrl_ value which is passed to the day navigation component in order to correct the URL.
:bug: Fixed issue with day navigation
> PIC-1007 Day Navigation Issue

- app.js
- server/routes/middleware/authorisationMiddleware.js
- server/views/autherror.njk
- server/views/error.njk
:bug: Fixed issue of blank screen when user role is incorrect
:recycle: Refactored auth middleware
:fire: Removed autherror template
:recycle: Included auth error in main error template
:wheelchair: Updated page title(s) on error page in order to improve a11y
> PIC-1086 Blank screen when user role missing or incorrect

- server/routes/middleware/defaults.js
As the court codes and names are currently hardcoded, changing this code in the URL causes  a crash in the frontend.
This fixes the issue but in these instances, the court name will of course not be displayed.
:bug: Unsupported court code causes front end to crash
> Unsupported court code causes front end to crash

- .circleci/config.yml
- Dockerfile
- README.md
- package-lock.json
- package.json
See: https://nodejs.org/en/blog/vulnerability/february-2021-security-releases/
:construction_worker: Updated CircleCI to use Node 14.16.0
:wrench: Updated project to use Node 14.16.0
:wrench: Updated Dockerfile to use Node 14.16.0
:memo: Updated Readme
:arrow_up: Updated dependencies
:wrench: Updated start:watch command to use npx
> Node.js February 2021 Security Releases

- config.js
- integration-tests/integration/features/select-court.feature
- server/views/select-court.njk
:lipstick: Split select courts UI into two columns
:wrench: Added short names for courts in config
> PIC-1166 Additional courts

- app.js
- config.js
Replaced express-session with cookie-session due to issues with express-session memory store capability of keeping the session info in memory in one of the pods. If another request comes in and hits another pod then it won't find the session and will consider the user logged out / or have to have an invalid session. This is causing issues for us when we increase the amount of pods.
> :adhesive_bandage: PIC-1173: added cookie-session

- server/routes/index.js
As per discussion with Chris, we need to change the probation status to null when unlinking a defendant
:bug: Fixed probation status when unmatching defendant
> PIC-1096 Probation Status

- helm_deploy/values-dev.yaml
- helm_deploy/values-preprod.yaml
I've added the ingress certificates in court-probation-dev and court-probation-preprod, so this PR references them in the app. We already have a certificate in prod. We need this for redis to work correctly.
> PIC-1196: added reference to ingress certs

- app.js
We're getting the error `Unable to verify authorization request state.`, after some googling it appears this may fix the issue, due to using a secure cookie in production - explains why it works locally!
Looking at other moj apps, they appear to have this code.
See https://www.npmjs.com/package/express-session#cookiesecure for more info.
> PIC-1196: set trust proxy

- server/routes/index.js
As we're putting the user preferences service live tonight I realised that if the user currently has the court cookie then they won't get the new onboarding journey and will therefore not store their chosen court(s) in the user preferences service.
In order to ensure all users will get the new experience I have chosen to rename the cookie to currentCourt.
I have also included some code to remove the old court cookie to make sure it's not hanging about on all our current users' machines.
We can remove this code at a later date.
♻️ Renamed the court cookie
🚧 Included code to remove the old cookie which will need to be removed at a later date.
> Rename court cookie

- integration-tests/integration/features/case-summary.feature
- mappings/community/D541487-conviction-1531139839.json
- mappings/community/D814575-conviction-241412130.json
- mappings/community/D985513-conviction-1679300004.json
- mappings/community/D991494-conviction-1361422142.json
- mappings/community/DX12340A-conviction-1309234876.json
- mappings/community/DX12340A-conviction-1403337513.json
- mappings/community/DX12340A-conviction-2360414697.json
- mappings/community/DX12340A-conviction-636401162.json
- mappings/community/DX12340A-requirements-2360414697.json
- mappings/community/E654321-conviction-345464567.json
- mappings/community/default-conviction.json
- server/routes/index.js
- server/services/community-service.js
- server/views/case-summary-record-order.njk
- tests/pact/community-service/get-conviction.test.pact.js
- tests/routes/view.test.js
- tests/services/community-service.test.js
- added functionality to point to single conviction endpoint from court-case-service, so we can use this instead of the costly probation-record endpoint when requesting data for a single conviction
- amended current single conviction endpoint to use the new single conviction endpoint 
- added unit tests for new functions
- added pact test for getConviction
- added BDD data for single conviction
> :zap: PIC-1175: Added new single conviction endpoint

- public/stylesheets/app/_overrides.scss
- server/views/case-summary-record.njk
Inline styles are blocked by CSP so I've replaced this with an override class.
This is unrelated to Google Analytics issues.
:recycle: Replaced inline style with new class
> Remove inline style

- config.js
- server/routes/index.js
:bug: Fix cookie expiry
The expiry for cookies stored for current court and analytics preference will now extend from the last visit to the application.
The user would now have to not use the application for 6 months to lose the cookie.
> Cookie fix

- app.js
- server/views/partials/layout.njk
After testing on Dev CSP was still blocking GA. I've updated this based on a blog post I found, looks like a belt & braces approach but...
:bug: Updated CSP to allow all GA connections/scripts
> PIC-1339 Fox Google Analytics 

- integration-tests/integration/features/case-list.feature
- integration-tests/integration/features/case-list/case-list.spec.js
- public/stylesheets/app/_overrides.scss
- server/views/case-list.njk
:sparkles: Added Go to today link on out of date range case list pages
:white_check_mark: Updated tests
:lipstick: Added no underline override
:coffin: Removed commented BDD tests
> PIC-1367 Past case list navigation

- integration-tests/integration/features/case-list.feature
- mappings/case-list/case-list-full.json
- server/utils/getCaseListFilters.js
- Added new probation status `Pre-sentence record` to filter. They are dynamic so the only options shown in the filters are what we have in the data, so this change will be ok to add before the back end work has been done - if we have no Pre-sentence record coming back in the data then it won't be an option in the filter.
- Added a BDD test to demonstrate that it works
- Updated mock data to include an example of `Pre-sentence record`
> Pic 1372 add pre sentence record to filter

- server/views/partials/layout.njk
The default load times uses 1% of the visitors for the measurement by default so the average is 0.
Looking at https://developers.google.com/analytics/devguides/collection/gtagjs/user-timings this looks to do what we need, so this is what the PR is for.
I've included it at the page end to make sure the event fires after the whole page has loaded.
> PIC-1391 GA page load times

- .circleci/config.yml
- Dockerfile
- README.md
- package-lock.json
- package.json
⬆️ Updated to use Node 14.17.0
⬆️ ajv 8.3.0  →   8.4.0
⬆️ axe-core 4.2.0  →   4.2.1
⬆️ @ministryofjustice/frontend 0.2.3  →   0.2.4
⬆️ govuk-frontend 3.11.0  →  3.12.0
> Upgrade Node and dependencies

- mappings/matching/probation-status-detail/default-probation-status-detail.json
- server/routes/index.js
🐛 Removed underscore in display of probation status on manual matching screen
> PIC-1204 Underscore in probation status on manual matching screen

- tests/pact/community-service/get-probation-record.test.pact.json
Removed the pssRequirements data to fix PACT, this isn't expected to return data in court-case-service when returning requirements and licenceConditions
> :white_check_mark: PIC-1439: removed pssRequirements data

- .gitattributes
This should enforce text end-of-line on all relevant files.
🔧 Introduce end-of-line normalization
> End-of-line normalization

- .circleci/config.yml
- Dockerfile
- README.md
- package-lock.json
- package.json
Node.js July 2021 Security Releases
See: https://nodejs.org/en/blog/vulnerability/july-2021-security-releases/
🔧 Update to use Node.js security release 14.17.3
📝 Updated README to specify Node.js version
⬆️ ajv 8.6.0  →  8.6.1
⬆️ cypress 7.6.0  →  7.7.0
⬆️ cypress-cucumber-preprocessor 4.1.2  →   4.1.3
⬆️ jest 27.0.5  →  27.0.6
⬆️ nodemon 2.0.7  →   2.0.9
⬆️ @ministryofjustice/frontend 0.2.4  →   0.2.5
⬆️ debug 4.3.1  →   4.3.2
⬆️ nock 13.1.0  →  13.1.1
⬆️ passport-oauth2 1.5.0  →   1.6.0
> node-security-release

- server/views/case-summary-record.njk
The author is now being populated correctly so this will show it again
> 🔥 Unhide author on probation record page

- tests/pact/case-service/update-case.test.pact.json
- tests/pact/user-preference-service/update-selected-courts.test.pact.js
Looks like the minor changes to Axios has caused this issue?
✅ Fix failing PACT tests
> Fix PACT tests

- config.js
After discussing with John, we've determined that the cause of the ClientAbortException alert could be that the backend has not yet responded due to a delay in the community API before the frontend times out.
We have agreed that a 4 second timeout should be acceptable for both handling a delay and not causing too much of a disruption to the user experience when a delay occurs.
🔧 Adjusted timeouts
> PIC-1595 Increase timeouts

- server/routes/index.js
Checked the pods this morning and there's been 1 restart due to a failed backend communication. This change should prevent the crash.
🐛 Correct issue causing crash if offenderDetail request fails
> 🚑️ Fix crash issue 

- app.js
Passport added code to regenerate the session in version 0.6.0. PaC already had code to destroy the session to achieve the same thing which was causing a conflict.
> 🐛 PIC-2549: Prevent session being destroyed/regenerated twice

- server/utils/getCaseListFilters.js
This is because the endpoint is changing its schema return when there's no data rather than giving an empty array. I didn't change it there as there's several other bits of code handling the same behaviour.
> fix: the case filter list fails when no cases come in.

- server/routes/handlers/outcomes/postActionsHandler.js
- server/views/outcomes/casesToResult.njk
Note the defendantId isn't consumed by the outcome assign function, a bug which existed prior to mass action being implemented and which has just come to light.
> fix: Pass defendantId along with hearingId to the mass action feature

- server/views/outcomes/casesInProgress.njk
When assigning a single case during mass assign the name was not following formatting standards set elsewhere on the page
> Update notification banner to use nunjucks filters for names

- server/utils/features.js
Add Oxford and Reading to Pilot Courts
> :wrench: Add Pilot Courts

- server/config.js
Currently users are experiencing timeouts with their average timing taking 8.5 seconds.
Increase the timeout to 20 seconds as a temporary patch until we resolve our performance issues.
> Increase default timeout to 20 seconds

- server/routes/handlers/caseSummary.js
- server/routes/handlers/outcomes/getMoveToResultedHandler.js
To get to the bottom of the mismatch of the uuid within the resulting call more logging is required for the event around the POST request. This will be removed once investigation is complete.
> Check for things in common with BE

- integration-tests/cypress/e2e/matching.feature
- server/config.js
- server/services/case-service.js
- tests/services/case-service.test.js
Setting the minimum match probability to zero, so that all the matching records are displayed and not filtered based on the filtration criteria.
> PIC-4268: Setting the minimum match probability to zero

- integration-tests/cypress/e2e/case-progress.feature
- integration-tests/cypress/e2e/case-summary-hearing-outcome.feature
- integration-tests/cypress/e2e/case-summary.feature
- integration-tests/cypress/support/step_definitions/common.js
- integration-tests/cypress/support/step_definitions/headings.js
- server/views/case-summary.njk
- server/views/components/key-details-bar/template.njk
- server/views/court-case-comments.njk
- server/views/court-case-progress.njk
Change the heading hierarchy on case-summary so that:
- The defendant name is a h1
- The title "Case Summary" is a large h2
- All other subsequent titles are medium h3s.
Moved the heading steps into their own file to focus what is going on outside of the monolithic common steps definition and focus on new steps that can test either the level or the level and the size either singularly or in a series.
Tempted to follow this up in a refactor to move everything to the same as we have multiple preexisting steps steps that test for the same thing but that will be a separate PR just to avoid losing sight of these changes.
> PIC 3142: Case summary information hierarchy

- package-lock.json
- package.json
- public/src/stylesheets/style.scss
- server/routes/index.js
- server/views/components/accessible-autocomplete/template.njk
- server/views/edit-courts.njk
[PIC-3136](https://dsdmoj.atlassian.net/browse/PIC-3136)
Improve a variety of accessibility points around our use of the accessible-autocomplete and the edit-courts page that it is used on.
- Upgrade the accessible-autocomplete package to v3.0.1 in order to make use of newer available parameters.
- NOTE: This has caused npm to re-evaluate the package-lock.json config and reformat/upgrade/remove redundancies. This will require some regression testing to be sure we're happy with these changes but cleaning this up is on our todo list so presenting it here for consideration.
- Compile accessible-autocomplete css before govuk-frontend, this makes no difference to mutually exclusive bootstrap classes but allow the `govuk-input-error` to override the accessibile-autocomplete classes and match …
> PIC 3136/text input improvements

- integration-tests/cypress/e2e/case-summary.feature
- integration-tests/cypress/e2e/case-summary/case-summary.steps.js
- server/views/case-summary.njk
[PIC-3149](https://dsdmoj.atlassian.net/browse/PIC-3149)
Update case summary offence heading to be h4 in line with the rest of the page.
Singular offence:
Multiple offences:
[PIC-3149]: https://dsdmoj.atlassian.net/browse/PIC-3149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIC-3149: Case Summary - Offences heading 

- public/src/stylesheets/app/_bootstrap-modal.scss
- server/views/components/modal/macro.njk
[[PIC-3143](https://dsdmoj.atlassian.net/browse/PIC-3143)]
A small change request by UCD, removing the left and right padding from the .modal-footer area so that the button align with the left hand content as based on the [Service Timeout](https://design.tax.service.gov.uk/hmrc-design-patterns/service-timeout/), which we are using as the design basis for our modals.
Left, before: footer has all around padding but notable on the left and right.
Right, after: footer still has padding on top and bottom but no longer on the left and right.
[PIC-3143]: https://dsdmoj.atlassian.net/browse/PIC-3143?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PIC 3143: Modal component, request UCD update

- integration-tests/cypress/e2e/case-summary.feature
- server/views/case-summary/partials/orders-previous/template.njk
Correct the date description on previous orders from 'Started on' to 'Ended on'.
On the left, as it is currently live (screenshot taken from Dev) and on the right, the correction: all Previous Orders now read as 'Ended on' as is correct.
> Hotfix: Previous orders date description correction.

- server/views/partials/case-details.njk
- server/views/partials/layout.njk
[PIC-3150](https://dsdmoj.atlassian.net/browse/PIC-3150): Move the case details sub-navigation out of the main-content so that it is skipped by the skip link
Previously, the block for sub navigation used in Case Details was a part of the main-content block. Given that main-content is the target of the skip link, this means any AT users relying on the A11Y DOM had to move over any-and all entries when present to reach the page specific content.
By moving it outside of the area, it will be skipped when the skip link is used whilst it remain a nav element so that shortcuts can easily move to it when navigation is desired.
New layout compared to old.
An example where no sub navigation rendered, no discernable difference:
An example of where sub navigation is rendered, critically where it is …
> PIC-3150: Case details skip link

- integration-tests/cypress/support/step_definitions/common.js
- server/views/case-search.njk
- server/views/components/search/template.njk
On case search error screen, adds "error" to title tag so screen readers read it out as soon as possible. Also ensures that error summary links to error field, complying with GDS guidelines.
Updates Cypress tests to assert the above.
> PIC-3232: Improve accessibility for case search errors

- integration-tests/cypress/e2e/case-progress.feature
- integration-tests/cypress/e2e/case-progress/steps.js
- integration-tests/cypress/e2e/case-summary-comments.feature
- integration-tests/cypress/e2e/case-summary-comments/steps.js
- server/routes/handlers/caseSummary.js
- server/routes/handlers/getAddCommentRequestHandler.js
- server/routes/handlers/getAddHearingNoteRequestHandler.js
- server/views/case-summary/case-summary.njk
- server/views/court-case-comments.njk
- tests/routes/handlers/getAddCommentRequestHandler.test.js
- tests/routes/handlers/getAddHearingNoteRequestHandler.test.js
Show success banner when adding a note or comment on a case
Update cypress tests to reflect this and remove some duplicate and unused test code
Success banner when adding a note:
Success banner when adding a comment:
> Pic 3148/show confirmation when a note is added

- integration-tests/cypress/e2e/case-summary.feature
- integration-tests/cypress/support/step_definitions/headings.js
- server/views/case-summary/case-summary-record.njk
- server/views/case-summary/case-summary-risk.njk
- Changed the headings "Probation Record" and "Risk Register" from h1 to h2 - retained the same styling so no visible change.
- Updated Cypress tests to reflect this.
> PIC-4537: improve heading hierarchy - probation record and risk register

- server/views/components/days-navigation/template.njk
Changed accessible names on datepicker to include visual label i.e. "Fri 29" rather than "Friday 29" as per recommendation from accessibility audit, to ensure compatibility with ATs.
Before:
Now:
> include visual label in accessible label for datepicker

- integration-tests/cypress/e2e/accessibility-statement.feature
- integration-tests/cypress/e2e/case-list.feature
- integration-tests/cypress/e2e/case-summary.feature
- integration-tests/cypress/e2e/cases-in-progress-list.feature
- integration-tests/cypress/e2e/cases-outcome-resulted.feature
- integration-tests/cypress/e2e/cases-to-result-list.feature
- integration-tests/cypress/e2e/cookies-policy.feature
- integration-tests/cypress/e2e/matching.feature
- integration-tests/cypress/e2e/outcomes.feature
- integration-tests/cypress/e2e/privacy-notice.feature
- integration-tests/cypress/e2e/select-court.feature
- integration-tests/cypress/e2e/user-guide.feature
- integration-tests/cypress/e2e/whats-new.feature
- server/views/partials/layout.njk
Migrates the feedback and bug forms from Google to Smart Survey and ServiceNow respectively. Update tests to reflect new URLs.
> replace google feedback forms with new links

- integration-tests/cypress/e2e/case-list.feature
- integration-tests/cypress/e2e/case-search.feature
- integration-tests/cypress/e2e/cases-in-progress-list.feature
- integration-tests/cypress/e2e/cases-outcome-resulted.feature
- integration-tests/cypress/e2e/cases-to-result-list.feature
- integration-tests/cypress/support/step_definitions/common.js
- server/routes/handlers/getPagedCaseListRouteHandler.js
- server/routes/handlers/matchRecords/matchingRecordRouteHandler.js
- server/utils/pagination.js
- server/views/case-list.njk
- server/views/case-search.njk
- server/views/match-defendant.njk
- server/views/outcomes/outcomes-paging-partial.njk
- tests/routes/handlers/caseSearchHandler.test.js
- tests/routes/handlers/getPagedCaseListRouteHandler.test.js
- tests/routes/handlers/matchRecords/matchingRecordRouteHandler.test.js
Changes PAC back to use MOJ Pagination rather than GDS pagination which was introduced in https://github.com/ministryofjustice/prepare-a-case/pull/1043/files and deployed to dev but not pre-prod or prod
We are changing it back to MOJ pagination so that the 'results' section can be retained
> use moj pagination in pac
