ministryofjustice/prepare-a-case

integration-tests/integration/features/ping.feature
package.json
routes/api.js
routes/middleware/healthcheck.js
routes/view.js
tests/routes/api.test.js
tests/routes/middleware/healthcheck.test.js
tests/routes/view.test.js
views/case-list.njk
views/dashboard.njk
yarn.lock

Added health check middleware, implemented on main view routes.
Includes unit tests

Healthcheck

---

integration-tests/integration/features/case-list.feature
mappings/case-list.json
mappings/empty-case-list.json
mappings/ping.json

Corrected matching so tests can run with correct format
Returns data with today's date and corrected session start times
Included static IDs

Tech Task - WireMock fixes

---

views/case-list.njk

Includes minor lint fixes
Signed-off-by: Paul Massey <paul.massey@scriptwerx.io>

Right align court room number and title

---

README.md
app.js
docker-compose.yml
package.json
tests/routes/api.test.js
tests/routes/view.test.js
yarn.lock

Having found a memory store suitable for production use I have removed Redis and replaced with memory store.
This should also be suitable for caching API requests in future.

Hotfix - Session store (PIC-304 - Correctly configure front end session)

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendant.js
mappings/community/D541487-convictions.json
mappings/community/DX12340A-convictions.json
package.json
views/case-summary-record-attendance.njk
yarn.lock

Updated start, end and termination reason for previous order
Aligned order end date with court-case-service
Updated dependencies

 PIC-357 Previous Order Header Details

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/previouslyKnownDefendant.js
mappings/community/D541487-convictions.json
mappings/community/DX12340A-convictions.json
views/case-summary-record.njk

Corrected end date on Probation record view
Added missing tests

BUGFIX Previous Order Date

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendant.js
mappings/community/DX12340A-convictions.json
package.json
services/case-service.js
views/case-summary-record-attendance.njk
yarn.lock

Includes provisional support for PIC-418 that will need to be checked in that ticket once the work on _court-case-service_ is done.

PIC-328 Unpaid Work

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendantWithBreach.js
mappings/community/D991494-attendance-1361422142.json
mappings/community/D991494-convictions.json
views/case-summary-record-attendance.njk

Does not show UPW attendance when there is no data

PIC-425 Hide UPW attendance when there is no data

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendant.js
mappings/community/D541487-convictions.json
mappings/community/D814575-convictions.json
mappings/community/D985513-convictions.json
mappings/community/D991494-attendance-1361422142.json
mappings/community/D991494-convictions.json
mappings/community/DX12340A-attendance-1403337513.json
mappings/community/DX12340A-convictions.json
package.json
views/case-summary-record-attendance.njk
views/case-summary-record.njk
yarn.lock

- Updated convictions test data to align with court-case-service response
- Added front end display for last pre-sentence report for current offender
- Added BDD tests

Pic 355 last pre sentence report

---

.circleci/config.yml
mappings/community/D991494-attendance-1361422142.json
mappings/community/DX12340A-attendance-1309234876.json
mappings/community/DX12340A-attendance-1403337513.json
views/case-summary-record-attendance.njk

Aligned data with court-case-service and updated mocks
Updated CircleCi config to use Node 12.16.2

PIC-418 Unpaid Work Status

---

package.json

Was just updating my own git pre-push hook to add in Snyk and figured I'd add it in to the npm command.

Add snyk to pre push hook command

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendantWithBreach.js
package-lock.json
package.json
views/case-summary-record.njk

Included Breach flag to Probation record view
Updated dependencies

PIC-346 Breach flag on Probation record view

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendantWithBreach.js
mappings/community/D991494-convictions.json
routes/middleware/defaults.js
services/community-service.js
views/case-summary-record-attendance.njk

Included breach information on detailed order view
Corrected a small issue with **Elapsed time** showing 0 months or days

PIC-347 Breach information

---

integration-tests/integration/common/common.spec.js
integration-tests/integration/features/case-summary.feature
integration-tests/integration/world/data/case-summary/currentDefendant.js
integration-tests/integration/world/data/case-summary/currentDefendantWithBreach.js
mappings/community/DX12340A-convictions.json
mappings/community/DX12340A-requirements-636401162.json
services/community-service.js
tests/services/community-service.test.js
views/case-summary-record-attendance.njk

- Added requirements at order summary view level for current orders.
- Added requirements at order summary view level for previous orders.
- Added BDD tests and wiremock data.
- In community-service.js for the requirements route, removed the condition for active convictions, as we also need requirements returned for previous orders.

PIC-336: added requirements to order summary view level

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendant.js
mappings/community/D541487-convictions.json
mappings/community/D814575-convictions.json
mappings/community/D985513-convictions.json
mappings/community/D991494-convictions.json
mappings/community/DX12340A-convictions.json
mappings/community/default-requirements.json
views/case-summary-record-attendance.njk
views/case-summary-record.njk

- added last OASys assessment details to probation record view
- added test data
- added BDD tests

PIC-354: added last oasys assessment to probation record view

---

views/case-summary-record.njk

Removed duplication after merge

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendantWithBreach.js
mappings/community/D991494-breach-54321.json
mappings/community/D991494-convictions.json
views/case-summary-record-order-breach.njk

Included Breach banner

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendant.js
mappings/community/DX12340A-convictions.json
views/case-summary-record-order.njk

Corrected text displayed on Licence and PSS headers.
Corrected spelling of licence throughout.
Corrected mock data.
Updated BDD tests.

PIC-363-Corrected-Text

---

helm_deploy/values-prod.yaml

Cloud platform has been updated to support the URL change with DNS zone created for `probation.service.justice.gov.uk`.
PR: https://github.com/ministryofjustice/cloud-platform-environments/pull/2517 has been merged.

PIC-454 Updated ingress.

---

helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml

PIC-454 Production Domain

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendant.js
integration-tests/integration/world/data/case-summary/currentDefendantWithBreach.js
integration-tests/integration/world/data/case-summary/previouslyKnownDefendant.js
mappings/community/D541487-convictions.json
mappings/community/D991494-convictions.json
mock_validation/community/common.js
package-lock.json
package.json
views/case-summary-record.njk

Updated last PSR date as per requirements
Updated mocks
Updated BDD to test new scenarios
Updated mock validation tests
Updated dependencies

PIC-467 Update last PSR date

---

helm_deploy/prepare-a-case/templates/_envs.tpl
helm_deploy/prepare-a-case/templates/deployment.yaml

Name of deployment container should be `prepare-a-case` instead of `court-case-service`
Also updated livenessProbe and readinessProbe endpoints to `/health`

Pic 492 fix deploy dev

---

app.js
config.js
helm_deploy/prepare-a-case/templates/_envs.tpl
helm_deploy/values-dev.yaml
helm_deploy/values-preprod.yaml
helm_deploy/values-prod.yaml
package-lock.json
package.json
server/authentication/auth.js

I've looked at the config and the envs set and some aren't used or are duplicated or unnecessary so I've cleaned these up.

Cleaned up redundant envs and config

---

integration-tests/integration/features/case-list.feature
integration-tests/integration/features/case-list/case-list.spec.js
server/views/case-list.njk

Simple change to add count of cases in the displayed case list, changes when filtered.
Added integration tests

Pic 581 count of cases

---

helm_deploy/prepare-a-case/templates/ingress.yaml

PIC-592 Disabled firewall for pen test

---

helm_deploy/values-preprod.yaml

PIC-589 Updated whitelist with IP addresses for Pen Test

---

integration-tests/integration/features/case-list.feature
integration-tests/integration/features/case-list/case-list.spec.js
package-lock.json
package.json
server/views/case-list.njk

As per conversation with Charan at standup, I've removed the filters from the case list when viewing recently added/removed case lists.

PIC-446 Hide Filters

---

app.js
helm_deploy/prepare-a-case/templates/_envs.tpl
package-lock.json
package.json
server/application-version.js
server/index.js
server/routes/middleware/populateCurrentUser.js
server/services/eventPublisher.js
server/utils/azure-appinsights.js
server/views/partials/layout.njk

Added Application Insights config
Added secrets in environments

Pic 541 add app insights

---

app.js
package-lock.json
package.json

Pass bearer token with Axios requests

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/world/data/case-summary/currentDefendant.js
integration-tests/integration/world/data/case-summary/currentDefendantWithBreach.js
mappings/community/D991494-sentence-1361422142.json
mappings/community/DX12340A-sentence-1309234876.json
mappings/community/DX12340A-sentence-1403337513.json
mock_validation/community/D991494-sentence-1361422142.test.js
mock_validation/community/DX12340A-sentence-1309234876.test.js
mock_validation/community/DX12340A-sentence-1403337513.test.js
mock_validation/community/common.js
server/views/case-summary-record-order.njk

Aligns the attendance data with court-case-service

---

package-lock.json
package.json

:arrow_up: Updates Cypress to 4.11.0

---

server/routes/index.js
server/services/community-service.js
server/services/utils/axios-error.js
server/services/utils/file-request.js
server/services/utils/request.js

Fixed minor issue in community-service
Removed console.log call for OM

PIC-641 Prevent logging of auth token

---

.circleci/config.yml
Dockerfile
bin/record-build-info
package.json
server/utils/azure-appinsights.js

Updated app insights config to include build info
Updated dockerfile to include build info

:loud_sound: Updated app insights config

---

helm_deploy/prepare-a-case/templates/ingress.yaml
helm_deploy/values-preprod.yaml

Restores firewall config and removes whitelisted IP addresses

Tech Task: Revert changes for pentest

---

integration-tests/integration/common/common.spec.js
integration-tests/integration/features/matching.feature
integration-tests/integration/features/matching/matching.spec.js
integration-tests/integration/world/World.js
integration-tests/integration/world/data/matching.js
integration-tests/integration/world/data/matching/bulkList.js
server/routes/index.js
server/views/case-list.njk
server/views/match-records.njk
server/views/partials/layout.njk
tests/routes/view.test.js

PIC-608 Bulk Matching Defendants

---

integration-tests/integration/common/common.spec.js
integration-tests/integration/features/matching.feature
integration-tests/integration/features/matching/matching.spec.js
integration-tests/integration/world/data/matching.js
integration-tests/integration/world/data/matching/defendantRecords.js
mappings/matching/3597035492-matches.json
mappings/matching/4172564047-matches.json
package.json
public/stylesheets/app/_inset-block.scss
public/stylesheets/app/_overrides.scss
public/stylesheets/app/all.scss
server/routes/index.js
server/services/case-service.js
server/views/case-summary.njk
server/views/match-defendant.njk
server/views/match-records.njk
server/views/partials/layout.njk
tests/jest.config.js
tests/routes/view.test.js
tests/services/case-service.test.js

Included match defendant screen and error message when submitting without selecting a radio button
Does correctly redirect on valid submission but does not send data to the backend, this will be picked up in the relevant story
Includes basic support and UI for PIC-611 and PIC-612 but no tests as these can be picked up there
Updated mocks
Added BDD tests
Fixed jest config

PIC-609 Review Defendant Match

---

integration-tests/integration/common/common.spec.js
integration-tests/integration/features/matching.feature
integration-tests/integration/features/matching/matching.spec.js
integration-tests/integration/world/data/matching.js
integration-tests/integration/world/data/matching/defendantOneRecords.js
integration-tests/integration/world/data/matching/defendantTwoRecords.js
mappings/matching/3597035492-confirm.json
mappings/matching/4172564047-confirm.json
mappings/matching/4172564047-matches.json
server/routes/index.js
server/services/case-service.js
server/services/utils/request.js
server/views/match-defendant.njk
tests/routes/view.test.js
tests/services/case-service.test.js

PIC-611 and PIC-612 - Included match confirmation functionality and UI messages

---

server/views/partials/header.html

BUGFIX: Header Link

---

integration-tests/integration/world/data/case-summary/currentDefendant.js
integration-tests/integration/world/data/case-summary/currentDefendantWithBreach.js
mappings/cases/5222601242.json
mappings/cases/6627839278.json
mappings/cases/668911253.json
server/views/case-summary.njk

PIC-722 Nationality bugfix

---

.circleci/config.yml
Dockerfile
README.md
package-lock.json
package.json

Updated dependencies.
Bumped Node version.

Updated dependencies

---

mappings/matching/3597035492-matches.json
mappings/matching/4172564047-matches.json
server/views/match-defendant.njk

Corrects data to display most recent event on match screen

PIC-725 BUGFIX - Invalid date on matching screen

---

integration-tests/integration/features/matching.feature
server/views/match-defendant.njk

Fixed Back link from match defendant screen
Included BDD tests

PIC-730 Back link not working

---

mappings/cases/2086970929.json
mappings/cases/2608860141.json
mappings/cases/2980462628.json
mappings/cases/5184555075.json
mappings/cases/7483843110.json
mappings/cases/8678951874.json
server/views/components/key-details-bar/template.njk

Fixed display of possible matches on case summary
Updated mock data to be more inline with live data

PIC-724 Possible nDelius record feature working incorrectly

---

app.js
package-lock.json
package.json

Removed bunyan-request-logger
Implemented basic request logging

Remove bunyan-request-logger

---

integration-tests/integration/world/data/case-summary/currentDefendant.js
mappings/community/DX12340A-convictions.json
server/views/case-summary-record-order.njk
server/views/case-summary-record.njk

Corrected current order start date
Also corrected issue with order length calculation

PIC-719 Current order start date

---

integration-tests/integration/features/case-list.feature
server/routes/index.js
server/views/case-list.njk

Display no matching cases when filtered list is empty

PIC-655 No cases match filters

---

server/views/case-summary-record-order.njk

Small change to fix the alignment of the awaiting outcome count

:bug: PIC-742: Fixed alignment for attendance awaiting outcome

---

integration-tests/integration/features/matching.feature
server/views/match-manual.njk

Changes to matcher error messages

---

helm_deploy/values-prod.yaml

See https://github.com/ministryofjustice/moj-ip-addresses/blob/master/moj-cidr-addresses.yml for IP range information

Update whitelist entry name to ark-internet

---

app.js
integration-tests/integration/features/matching.feature
integration-tests/integration/features/matching/matching.spec.js
public/stylesheets/app/_overrides.scss
server/views/match-defendant.njk

Highlight matching defendant details

PIC-610 Highlight matching

---

app.js
integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendant.js
mappings/community/DX12340A-requirements-1309234876.json
mappings/community/DX12340A-requirements-2360414697.json
server/views/case-summary-record.njk

- added pss requirements to probation record view
- added licence conditions to probation record view
- updated mock data
- added BDD tests

Pic 361 pss requirements probation record

---

integration-tests/integration/features/case-list.feature
server/views/case-list.njk

Updated to display 0 cases when no filtered cases

PIC-655 No Filtered Cases

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
mappings/community/DX12340A-requirements-1309234876.json
mappings/community/DX12340A-requirements-2360414697.json
server/views/case-summary-record-order.njk

2 tests are not passing and I don't know why... I would be happy to have help on these! :)
View the probation record section of the case summary for a current offender
View the probation record to see the post-sentence supervision requirements attached to a current custodial order.

PIC - 364 Order summary - Current custodial order requirements & logic

---

integration-tests/integration/world/data/case-summary/currentDefendant.js
mappings/community/DX12340A-convictions.json
server/views/case-summary-record-order.njk
server/views/case-summary-record.njk

Simple change, added order length to order summary title

Pic 765 display order length in order summary

---

package-lock.json
package.json

Updated Debug to 4.2.0
Updated GOVUK Frontend to 3.9.1
Updated Moment to 2.29.0
Updated Cypress to 5.2.0
Updated Swagger Client to 3.11.0

Updated project dependencies

---

mappings/community/D991494-breach-54321.json
mappings/community/D991494-breach-98765.json
server/views/case-summary-record-order-breach.njk

:bug: Fixed issue with breach attachments not being displayed
:clown_face: Corrected mock data

PIC-766 Breach Attachments

---

public/stylesheets/app/_badge.scss
server/views/components/key-details-bar/template.njk

Ensure Possible nDelius record is not displayed for No record

---

mappings/cases/6627839278.json
package-lock.json
package.json
server/views/case-list.njk
server/views/components/key-details-bar/template.njk
server/views/match-defendant.njk
server/views/match-manual.njk
server/views/match-unlink.njk

:lipstick: Corrected display of probation status throughout
:arrow_up: Updated Cypress to 5.3.0
:arrow_up: Updated Supertest to 5.0.0

Fix probation status and upgrade dependencies

---

mappings/community/DX12340A-requirements-1309234876.json
mappings/community/DX12340A-requirements-2360414697.json
server/views/case-summary-record.njk

- Added correct reference to pss requirements and licence conditions
- Updated mock data to align with court-case-service

:bug: PIC-361: Fixed missing pss requirements and licence conditions on probation record

---

mappings/cases/2608860141.json
mappings/cases/3597035492.json
mappings/cases/4172564047.json
server/views/case-list.njk
server/views/components/key-details-bar/template.njk

:bug: Fixed duplicate status being displayed
:bug: Fixed display of link / unlink button

PIC-760 Duplicate status

---

integration-tests/integration/features/case-summary.feature
server/views/case-summary-record-order.njk
server/views/case-summary-record.njk

In order to close this ticket and start a new one -> Charan

Pic364 - PSS and Licence Condition appearing BOTH on summary and order

---

server/views/select-court.njk

:recycle: Reversed court selection order

---

server/views/select-court.njk

:lipstick: Changed link font weight

PIC-780 Font weight change

---

server/routes/attachments.js
server/services/community-service.js

:bug: Fix incorrect headers for attachments

PIC-785 Document incorrect headers

---

server/views/case-summary.njk

https://dsdmoj.atlassian.net/browse/PIC-808

✏️   1 possible record banner content change

---

integration-tests/integration/features/case-list/case-list.spec.js
server/views/case-list.njk

Possible records CTA content change
https://dsdmoj.atlassian.net/browse/PIC-809

✏️ PIC-809 - Possible records CTA content change

---

integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/world/data/case-summary/currentDefendantWithBreach.js
mappings/community/D991494-breach-12345.json
mappings/community/D991494-breach-54321.json
mappings/community/D991494-breach-98765.json
server/views/case-summary-record-order-breach.njk
server/views/case-summary-record-order.njk

- Breach response fields have changed in court-case-service so I have updated the fields in mock data, the breach view and integration tests.

PIC-840: Updated fields for breach response

---

server/views/case-summary-record-order.njk

:bug: Corrected last attended information

PIC-810 Last Attended

---

server/services/case-service.js

:bug: Ensure filters are not applied to added and removed cases

PIC-807 Ignore filters on added & removed case list views

---

config.js
server/routes/middleware/defaults.js
tests/routes/middleware/defaults.test.js

:sparkles: Reconfigured case list navigation and initial support fo dynamic working days.

PIC-878 Case List Navigation

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
server/routes/index.js

https://dsdmoj.atlassian.net/browse/PIC-869

🐛 Breadcrumbs - 'Back to cases' link takes you back to the previous list you were working

---

integration-tests/integration/world/data/case-summary/currentDefendant.js
server/views/case-summary-record.njk

- Updated formatting for requirement subTypes, replaced `-` with en-dash `–`
- Removed brackets
- Updated BDD tests

:lipstick: PIC-867: Updated formatting for requirement subTypes

---

mappings/community/D541487-convictions.json
mappings/community/D814575-convictions.json
mappings/community/D985513-convictions.json
mappings/community/D991494-convictions.json
mappings/community/DX12340A-convictions.json
mappings/community/E654321-convictions.json
mock_validation/common.js
server/views/case-summary-record-order.njk

- Updated to use conviction.sentence.endDate field instead of conviction.endDate field
- Updated mock data

:art: PIC-842: Updated to use sentence endDate field

---

server/views/case-summary-risk.njk

The column width change seems to have been done previously...
https://dsdmoj.atlassian.net/browse/PIC-844

💄PIC-844 : Risk register date transform

---

integration-tests/integration/features/case-summary.feature
mappings/community/D991494-breach-12345.json
mappings/community/D991494-breach-54321.json
mappings/community/D991494-breach-98765.json
server/views/case-summary-record-order-breach.njk

- Added notes section to breach, displaying notes if available and `No notes have been added` if not
- Added notes to breach mock data
- Added BDD tests

PIC-904: Added notes section to breach

---

integration-tests/integration/features/matching.feature
integration-tests/integration/world/data/matching/defendantOneRecords.js
integration-tests/integration/world/data/matching/defendantTwoRecords.js
mappings/cases/3597035492.json
mappings/matching/3597035492-matches.json
server/views/match-defendant.njk

:sparkles: Include middle name(s) on matching screen

PIC-918 Middle names on matching screen

---

.circleci/config.yml
.gitignore
Dockerfile
package-lock.json
package.json

As part of PIC-305, I wasn't happy that the CSS build and Minify wasn't setup properly in the CI and Dockerfile (because it was being awkward) so I fixed it and updated some dependencies too.
:hammer: Update build scripts for Circle and Docker
:arrow_up: Upgrade dependencies

PIC-305 UI Components

---

integration-tests/integration/features/case-summary.feature
mappings/community/DX12340A-requirements-1309234876.json
mappings/community/DX12340A-requirements-2360414697.json
server/routes/index.js
server/views/case-summary-record-order-licence.njk
server/views/case-summary-record-order.njk
tests/routes/view.test.js

- Added licence conditions details
- Updated mocks
- Updated integration tests and unit tests

:sparkles: PIC-915: Added licence condtions details

---

integration-tests/integration/features/case-summary.feature
mappings/community/D991494-sentence-1361422142.json
mappings/community/DX12340A-sentence-1309234876.json
mappings/community/DX12340A-sentence-1403337513.json
mappings/community/DX12340A-sentence-2360414697.json
mappings/community/E654321-sentence-99483532.json
server/views/case-summary-record-order.njk

:sparkles: Included deep link to NDelius
:clown_face: Updated mocks
:white_check_mark: Updated integration tests

PIC-654 NDelius Contacts Link

---

integration-tests/integration/features/case-summary.feature
public/stylesheets/app/_key-details.scss
server/views/components/key-details-bar/template.njk

Having spoken with Charan we've agreed (now that we will have PNC) to make the Probation status always appear on the line below the name.
I've used Flexbox as we only have to go back to IE11 and this seems best suited to achieve what we're after.

PC-929 Key Details Bar Refinement

---

app.js
package-lock.json

:lock: Updated helmet to include Content Security Policy
:arrow_up: Fixed security issue after npm audit

PIC-947 Content-Security-Policy

---

integration-tests/integration/features/case-summary.feature
server/views/case-summary-record-order.njk

Suppress 'Awaiting outcome' when count is 0

---

integration-tests/integration/features/case-list.feature
server/views/case-list.njk

:children_crossing: Suppress filters when there are no cases

PIC-919 Suppress Filters

---

integration-tests/integration/features/matching.feature
mappings/case-list-full.json
mappings/cases/2608860141.json
mappings/cases/3597035492.json
mappings/cases/5184555075.json
mappings/cases/6627839278.json
mappings/cases/7483843110.json
mappings/cases/8678951874.json
server/utils/nunjucksSetup.js
server/views/case-list.njk
server/views/case-summary.njk
server/views/components/match-confirmation/template.njk
server/views/match-defendant.njk
server/views/match-manual.njk
server/views/match-records.njk
server/views/partials/case-details.njk

- Added custom nunjucks filter to check name for titles using regex and replace with empty string if present
- Updated mock data to include titles in `defendantName` so reflects real data and can make sure the filter works correctly.

:sparkles: PIC-866: Removed defendant title

---

config.js
integration-tests/integration/features/select-court.feature
server/routes/index.js
server/routes/middleware/defaults.js
server/views/select-court.njk
tests/routes/middleware/defaults.test.js

:sparkles: Updated list of available courts
:wrench: Updated config to include available courts
:white_check_mark: Added integration tests for court selection page
:white_check_mark: Updated unit tests

PIC-992 Updated available courts

---

.circleci/config.yml
Dockerfile
package-lock.json
package.json

:arrow_up: Upgrade node dependencies
:construction_worker: Update CircleCI config to use Node 14.15.3
:hammer: Update Dockerfile to use Node 14.15.3

Upgrade dependencies and config files

---

integration-tests/integration/features/case-summary.feature
mappings/community/DX12340A-sentence-1309234876.json
server/views/case-summary-record-order.njk

:bug: Corrected issue with appointments awaiting outcome

PIC-1008 Awaiting outcome appointments

---

server/routes/index.js
server/services/community-service.js
tests/routes/view.test.js

:zap: Improved performance by removing unnecessary API calls

PIC-989 Case Summary Performance

---

integration-tests/integration/features/matching.feature
server/routes/index.js
server/views/match-manual.njk

:bug: Corrected manual match Cancel link depending on previous page
:white_check_mark: Added test for the Cancel link

PIC-1022 Manual match Cancel link

---

package-lock.json
package.json
server/routes/index.js
server/views/match-unlink.njk
server/views/partials/case-details.njk

:bug: Fixed back link of case summary views
:arrow_up: Upgraded dependencies

PIC-1032 Back link on case summary views

---

integration-tests/integration/features/matching.feature
package-lock.json
package.json
server/views/match-manual.njk

:sparkles: Added back link to manual matching screen
:white_check_mark: Updated tests to test new back link
:arrow_up: Updated dependencies

PIC-1031 Back link on manual matching screen

---

server/routes/index.js

:recycle: Chain response cookie and redirect, ensure correct response codes are used

PIC-1049 Select Court Issue

---

server/routes/index.js

:recycle: Refactors
:fire: Removed erroneous use of cookies in select-court route
:fire: Removed erroneous use of health middleware

PIC-1049 Select Court

---

README.md
package-lock.json
package.json

:arrow_up: Upgrade dependencies
:memo: Updated Node version in README

Upgrade dependencies

---

server/routes/index.js
server/routes/middleware/healthcheck.js
server/services/case-service.js
server/services/community-service.js
server/utils/nunjucksSetup.js
server/views/case-summary.njk
server/views/components/key-details-bar/template.njk
server/views/error.njk
server/views/match-unlink.njk
tests/routes/middleware/healthcheck.test.js
tests/routes/view.test.js

:bug: Corrected use of health middleware
:recycle: Refactored health middleware to use config
:white_check_mark: Updated tests
:bug: Corrected rendering errors throughout when backend service returns unexpected response

PIC-1084 Backend Service Down

---

package-lock.json
package.json

:arrow_up: Update supertest to 6.1.3

Bump supertest to 6.1.3

---

.snyk

Include Snyk policy

---

config.js
server/services/case-service.js
server/utils/getLatestSnapshot.js
tests/services/case-service.test.js
tests/utils/getLatestSnapshot.test.js

:sparkles: Included latest snapshot in case list request

PIC-1098 Case List Snapshot

---

helm_deploy/values-preprod.yaml

:wrench: Update deployment to provide AnyConnect access to preprod

AnyConnect access to PreProd

---

integration-tests/integration/common/common.spec.js
integration-tests/integration/features/user-guide.feature
public/stylesheets/app/_overrides.scss
server/routes/index.js
server/views/partials/layout.njk
server/views/user-guide.njk
tests/routes/view.test.js

PIC-1174 User Guide

---

app.js
config.js

I've raised a few PR's when adding the cookie-session so thought it would be easier to remove cookie-session in a new PR rather than reverting the others.

PIC-1173: Removed cookie-session

---

public/stylesheets/app/_overrides.scss
server/views/user-guide.njk

Updates after QA from Alastair and Charan.
:lipstick: Updated UI and corrected headings

PIC-1174 User Guide Changes

---

mappings/matching/3597035492-detail.json
mappings/matching/3597035492-probation-status-detail.json
mappings/matching/default-probation-status-detail.json
server/routes/index.js
server/services/community-service.js
tests/pact/community-service/get-probation-status-details.test.pact.js
tests/routes/view.test.js
tests/services/community-service.test.js

:bug: Corrected issue with probation status
:alien: Updated to use new endpoint to fetch up-to-date probation status data
:white_check_mark: Updated tests
:white_check_mark: Included PACT test for new endpoint
:clown_face: Included mocks for new endpoint

PIC-1197 Probation Status

---

.circleci/config.yml
README.md
app.js
config.js
docker-compose.test.yml
docker-compose.yml
helm_deploy/prepare-a-case/templates/_envs.tpl
package-lock.json
package.json

🔧  Added redis config to app.js
🔧  Added environment variables to connect with elasticache values in namespaces
🔧  Added docker-compose.test file to run redis when running integration tests
🔧  Updated circle config to include redis
📝  Updated readme

:rocket: PIC-1196: added redis

---

mappings/case-list-full.json
server/views/case-summary.njk
server/views/match-records.njk

:bug: Fixed issue with defendant name not displaying

PIC-1215  - Defendant Name Not Displaying

---

helm_deploy/prepare-a-case/templates/_envs.tpl

Build failed as missing USER_PREFERENCE_SERVICE_URL env var in `.envs.tpl`

:wrench: added USER_PREFERENCE_SERVICE_URL env var

---

tests/utils/getLatestSnapshot.test.js

:bug: Fix locally failing test

BUGFIX: Fix locally failing unit test

---

package-lock.json
package.json

:arrow_up: Upgrade and pin dependencies

Tech Task - Upgrade dependencies

---

config.js
server/routes/index.js
server/views/case-list.njk

:recycle: Updated to control notification with simple config change

PIC-1273 Notification Banner (change)

---

config.js

Refering to the last spreadsheet
Update here and in the pod in crime-portal-gateway

PIC-1292 and PIC-1291 : Add court

---

integration-tests/integration/features/case-summary.feature
mappings/community/D541487-convictions.json
mappings/community/D814575-convictions.json
mappings/community/D985513-convictions.json
mappings/community/D991494-convictions.json
mappings/community/DX12340A-convictions.json
mappings/community/E654321-convictions.json
server/views/case-summary-record.njk

- Updated mock data to include new fields for offender manager contact details
- Updated view to display contact details
- Added BDD tests

:sparkles: PIC-1269: Added offender manager contact details

---

integration-tests/integration/features/privacy-notice.feature
server/routes/index.js
server/views/partials/layout.njk
server/views/privacy-notice.njk

- added link in footer to privacy notice 
- created privacy notice page
- added new end point for privacy page
- added new feature for privacy notice

:sparkles: PIC-1287: add privacy notice

---

server/views/privacy-notice.njk

- added brackets around url as requested by Alastair

:lipstick: PIC-1287: added brackets around url

---

app.js
server/views/partials/layout.njk

Fix Google Analytics

---

app.js

🔊 Switch startup message from bunyan

PIC-1324 Startup Message

---

tests/pact/user-preference-service/get-selected-courts.test.pact.js
tests/pact/user-preference-service/update-selected-courts.test.pact.js

PIC-1194 User Preferences PACT

---

server/views/error.njk

:fire: Remove cookie banner from error page

Remove cookie banner from error page

---

config.js

:fire: Removes the banner message

Removes the banner message

---

integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/case-summary/case-summary.spec.js
integration-tests/integration/features/matching.feature
mappings/case-list/case-list-full.json
mappings/cases/7483843110.json
server/views/partials/case-details.njk

PIC-1290 is really a backend ticket but this is just to make sure we have this scenario covered in the frontend and some BDD around it.
✅ Added tests to ensure pre-sentence record displays correctly

PIC-1290 Pre-sentence record

---

integration-tests/integration/features/case-summary.feature
server/views/partials/case-details.njk

🚑 HOTFIX: Show case summary nav on pre-sentence record

---

integration-tests/integration/common/common.spec.js
integration-tests/integration/features/accessibility-statement.feature
integration-tests/integration/features/case-list.feature
integration-tests/integration/features/case-summary.feature
integration-tests/integration/features/cookies-policy.feature
integration-tests/integration/features/matching.feature
integration-tests/integration/features/privacy-notice.feature
integration-tests/integration/features/select-court.feature
integration-tests/integration/features/user-guide.feature
public/stylesheets/app/_overrides.scss
server/views/partials/layout.njk

✨ Included feedback banner
✅ Updated BDD tests

PIC-1384 Feedback banner

---

public/stylesheets/app/_header.scss
server/views/partials/header.html

🔥 Removed BETA badge from header

PIC-1420 Remove BETA badge from header

---

integration-tests/integration/features/case-list.feature
integration-tests/integration/features/case-summary.feature
server/views/case-list.njk

🔥 Removed Cases caption on case list

PIC-1419 Remove cases caption from case list

---

server/routes/index.js
server/views/match-manual.njk

PIC-1412 CRN Validation

---

mappings/case-list/case-list-full.json
mappings/case-list/case-list-short.json
mappings/cases/2086970929.json
mappings/cases/2608860141.json
mappings/cases/2980462628.json
mappings/cases/351196424.json
mappings/cases/3597035492.json
mappings/cases/4172564047.json
mappings/cases/5184555075.json
mappings/cases/5222601242.json
mappings/cases/5629289820.json
mappings/cases/6627839278.json
mappings/cases/668911253.json
mappings/cases/7483843110.json
mappings/cases/8678951874.json
mappings/cases/default.json
schemas/get-case-list.schema.json
schemas/get-case.schema.json
schemas/put-case.schema.json
tests/pact/case-service/get-case.test.pact.json
tests/pact/case-service/update-case.test.pact.js
tests/pact/case-service/update-case.test.pact.json

👽 Updated to support `awaitingPsr` flag.
👽 Improved PUT case schema.

PIC-1431 Support awaiting PSR in consumer mocks and PACT tests

---

integration-tests/integration/features/matching.feature
mappings/matching/detail/3608860223-detail.json
mappings/matching/detail/default-detail.json
schemas/get-details.schema.json
server/routes/index.js
server/views/match-manual.njk

🐛  Added error text when limited access marker (403) returned from court-case-service when doing a manual match
✅ Added BDD test
🤡  Updated mocks

Pic 1418 lam manual linking text

---

mappings/cases/3597035492.json
mappings/matching/matches-detail/3597035492-matches.json
schemas/get-case.schema.json
schemas/get-match-details.schema.json
server/views/match-defendant.njk

Fixed issue when no PNC is returned

PIC-1453 - BUGFIX - missing PNC

---

server/routes/index.js
tests/routes/view.test.js

👽 Include awaitingPsr when updating manual match

PIC-1450 Include awaitingPsr in manual match

---

.circleci/config.yml
README.md
package-lock.json
package.json

⬆️ wiremock-standalone-2.27.2.jar → wiremock-jre8-standalone-2.28.1.jar
⬆️ cypress  7.4.0 → 7.5.0

Upgrade Wiremock and Cypress

---

app.js
config.js
helm_deploy/prepare-a-case/templates/_envs.tpl
package-lock.json
package.json
server/routes/index.js
server/routes/middleware/populateCurrentUser.js
server/views/case-list.njk
server/views/set-notification.njk
tests/testUtils/appSetup.js

Set NOTIFICATION_USERNAME and NOTIFICATION_PASSWORD for testing.
I've added these to the secret in k8s dev, preprod and prod.
✨ Included route to set notification text.
🛂 Included simple username and password for notification setting
🔧 Updated config to use notification username and password
♻️ Moved getAsync and setAsync to req.redisClient

PIC-1482 Notification Banner

---

helm_deploy/prepare-a-case/templates/_envs.tpl

🐛 Corrected password env var setting

Notification password fix

---

server/views/partials/layout.njk

PIC-1345 Google Analytics

---

integration-tests/integration/features/case-summary.feature
mappings/community/convictions/D541487-convictions.json
server/views/case-summary-record.njk

🐛 Do not display last PSR without completion date

PIC-1519 PSR NaN Date

---

app.js
server/errorHandler.js
server/routes/index.js

On the request for access email, I noticed that the attached screenshot had no styling applied, this is because the `nonce` and `appVersion` are stored in res.locals incorrectly. This PR fixes this.
🐛 Fix error loading assets on authError

PIC-1535 - Auth error route

---

integration-tests/integration/features/case-summary.feature
mappings/community/convictions/D541487-convictions.json
mappings/community/convictions/D814575-convictions.json
mappings/community/convictions/D985513-convictions.json
mappings/community/convictions/D991494-convictions.json
mappings/community/convictions/DX12340A-convictions.json
mappings/community/convictions/E654321-convictions.json
mappings/community/convictions/V654123-convictions.json
schemas/get-probation-record.schema.json
server/views/case-summary-record.njk
tests/pact/community-service/get-probation-record.test.pact.json

✨ added pre-sentence report request info to probation-record page
🤡 updated mock data for probation-record endpoint to include psr data and 2 new fields `main` and `offenceDate` to offences
✅ added integration tests for new feature
✅ updated pact schema and tests

Pic 1521 add psr

---

server/views/case-summary-record.njk

🐛 Corrected bug in awaiting PSR data sorting

PIC-1521 Fix

---

integration-tests/integration/features/case-summary.feature
mappings/community/convictions/D541487-convictions.json
mappings/community/convictions/DX12340A-convictions.json
server/views/case-summary-record.njk

🐛 Fixed bug with display of PSR information
🤡 Corrected mock data for PSR by removing sentence
✅ Updated test for PSR information

PIC-1521 PSR fixes and refactoring

---

mappings/community/sentence/D991494-sentence-1361422142.json
mappings/community/sentence/DX12340A-sentence-1309234876.json
mappings/community/sentence/DX12340A-sentence-1403337513.json
mappings/community/sentence/DX12340A-sentence-2360414697.json
mappings/community/sentence/E654321-sentence-99483532.json
server/routes/index.js
server/services/community-service.js
tests/pact/community-service/get-sentence-details.test.pact.js
tests/pact/community-service/get-sentence-details.test.pact.json
tests/routes/view.test.js
tests/services/community-service.test.js

👽  Updated to use new court-case-service sentence endpoint `/offender/{crn}/convictions/{convictionId}/sentence`
✅  Updated tests
🤡  Updated mocks

:alien:  PIC-1534: Updated to use new sentence endpoint

---

mappings/community/conviction/V654123-conviction-345464567.json
mappings/community/custody/2360414697-sentence-custody.json
mappings/community/custody/345464568-sentence-custody.json
mappings/community/sentence/D991494-sentence-1361422142.json
mappings/community/sentence/D991494-sentence-345464567.json
mappings/community/sentence/DX12340A-sentence-1309234876.json
mappings/community/sentence/DX12340A-sentence-1403337513.json
mappings/community/sentence/DX12340A-sentence-2360414697.json
mappings/community/sentence/E654321-sentence-99483532.json
mappings/community/sentence/V654123-sentence-99483532.json
schemas/get-sentence.schema.json
server/views/case-summary-record-order.njk
tests/pact/community-service/get-sentence-details.test.pact.json

🤡 Updated mocks to represent new CCS sentence data structure
🔥 Removed reference to `currentOrderHeaderDetail` in single conviction, updated to use `releaseDate` instead of `disposalDate`
💄 Updated UI 
✅ Updated integration tests
✅ Updated PACT

Pic 1569 reorganise sentence response

---

integration-tests/integration/features/case-summary.feature
server/views/case-summary-record-order.njk

:pencil2: PIC-1577: fix typo

---

mappings/community/custody/2360414697-sentence-custody.json
mappings/community/sentence/DX12340A-sentence-2360414697.json

:green_heart:    PIC-1577: fix integration test

---

server/views/case-summary-record-order.njk

I also noticed a bug when the offender is in custody so have fixed that also.

:bug: PIC-1579: fix post release dates bug

---

server/views/case-summary-record-order.njk

:loud_sound: add temp data dump

---

mappings/community/sentence/D991494-sentence-1361422142.json
server/views/case-summary-record-order.njk

:bug: PIC-1569: fix pss issues

---

mappings/community/sentence/DX12340A-sentence-1309234876.json
server/views/case-summary-record-order.njk

:bug: fix pss and licence status

---

.circleci/config.yml
Dockerfile
package.json

:arrow_up: Upgrade node

---

.circleci/config.yml
Dockerfile
README.md
package-lock.json
package.json

⬆️ Upgrade Node and dependencies
⬆️ Upgrade WireMock standalone
📝 Update README

Upgrade node, wiremock and dependencies

---

server/views/case-summary-record-order.njk

PIC-1625 Licence date

---

integration-tests/integration/common/common.spec.js
integration-tests/integration/features/case-summary.feature
mappings/community/custody/2360414697-sentence-custody.json
server/views/case-summary-record-order.njk

After discussion with Alastair we've determined that the data from the new endpoint (displayed in the table below) is correct so we have included this information in the top section and set it to not display if this is absent from the retuned data just incase.

PIC-1625 licence pss date

---

app.js

- added helmet csp directive to display iframe correctly

:bug:  PIC-1578: add csp directive

---

schemas/get-case-list.schema.json

:white_check_mark:   PIC-1752: fix pact

---

integration-tests/integration/features/case-summary.feature
server/views/case-summary.njk

🔥 Remove listing from case summary
✅ Updated integration tests

PIC-1940 Remove listing from case summary

---

server/views/case-summary.njk

💬 Added full stop (nDelius already updated to NDelius)

PIC-1573 Possible records content change

---

integration-tests/integration/features/case-summary.feature
server/views/case-summary-record-order.njk

💬 Updated L2 heading
✅ Updated integration tests

PIC-1669 Post-release date content change

---

.circleci/config.yml
Dockerfile
README.md
package-lock.json
package.json

⬆️ Upgrade dependencies
🔧 Update package.json to require Node 16.14.0
👷 Update CI to use Node 16.14.0
📝 Update README

Upgrade Node and dependencies

---

mappings/matching/matches-detail/3597035492-matches.json
mappings/matching/matches-detail/4172564047-matches.json
mappings/matching/matches-detail/8678951874-matches.json
server/routes/index.js
server/services/case-service.js
tests/pact/case-service/get-match-details.test.pact.js
tests/pact/case-service/get-match-details.test.pact.json
tests/routes/view.test.js
tests/services/case-service.test.js

Should be merged after https://github.com/ministryofjustice/court-case-service/pull/808

PIC-2165 use offender match endpoint without case id

---

integration-tests/integration/features/matching.feature

⏪️ Reinstate integration test for matching feature

Reinstate integration test for matching feature

---

package-lock.json
package.json

⬇️ Revert Helmet update from March

PIC-2121 : User guide videos not displaying

---

server/routes/index.js
server/views/set-notification.njk

🚸 Add expiry option for user notification

---

public/javascripts/filter-component.js

♿️ Correct behaviour of filters component when navigating with the keyboard

PIC-2157 - Filters component a11y issue

---

.circleci/config.yml
Dockerfile
package.json

Should fix the image scan issue
⬆️ Upgrade to use Node 16.17.0

Upgrade Node

---

server/views/partials/layout.njk

This reverts commit 9dfaa6930ed77c790d0a8ea6589eead6940d8556.

Revert "📈 PIC-2385: Add google tag manager snippets (#666)"

---

integration-tests/integration/features/case-list.feature
integration-tests/integration/features/case-list/case-list.spec.js
integration-tests/integration/features/whats-new.feature
server/routes/index.js
server/utils/features.js
server/views/partials/layout.njk
server/views/whats-new.njk
tests/routes/handlers/getCaseListRouteHandler.test.js
tests/utils/featureTogglePredicates.test.js

Please don't merge it until the feature are made live. Check with @RebeccaCryan

PIC-2653: ✨ Add Whats new page + BDD tests

---

integration-tests/integration/features/cookies-policy.feature
server/views/cookies-policy.njk

Just updating the cookie page when the app insights flag is true :)

:speech_balloon: Update cookie Policy

---

server/views/user-guide.njk

Updates as per - https://dsdmoj.atlassian.net/jira/software/c/projects/PIC/boards/980?modal=detail&selectedIssue=PIC-3272&assignee=63fe35670a4a47fb8d213f5d

PIC-3272 - Update user-guide.njk

---

integration-tests/integration/features/whats-new.feature
server/views/whats-new.njk

Update What's new with https://dsdmoj.atlassian.net/jira/software/c/projects/PIC/boards/980?modal=detail&selectedIssue=PIC-3271&assignee=63fe35670a4a47fb8d213f5d

Pic 3271 - Update what's new

---

server/routes/handlers/getCaseListRouteHandler.js
server/routes/handlers/getPagedCaseListRouteHandler.js
server/routes/middleware/outcomesMiddleware.js
server/views/partials/layout.njk
tests/routes/handlers/getCaseListRouteHandler.test.js
tests/routes/handlers/getPagedCaseListRouteHandler.test.js

* PIC-3359 grant hearing outcomes access to PIC team in preprod
* PIC-3359 fix hearing outcomes feature toggle

Pic 3359 fix feature toggling

---

integration-tests/cypress/e2e/assign-outcome.feature
integration-tests/cypress/e2e/cases-to-result-list-filter.feature
integration-tests/cypress/e2e/cases-to-result-list.feature
integration-tests/cypress/e2e/matching.feature
integration-tests/cypress/e2e/outcomes-to-result-mass-action-assign.feature
integration-tests/cypress/e2e/outcomes-to-result-mass-action-assign/steps.js
integration-tests/cypress/e2e/outcomes.feature
integration-tests/cypress/support/step_definitions/common.js
package-lock.json
package.json
public/config/external.js
public/src/javascripts/checker_toggle.js
public/src/stylesheets/app/_global.scss
public/src/stylesheets/app/_splide_carousel.scss
public/src/stylesheets/app/all.scss
public/src/stylesheets/style.scss
server/app.js
server/routes/handlers/outcomes/getCasesToResultHandler.js
server/routes/handlers/outcomes/outcomesRouter.js
server/routes/handlers/outcomes/postActionsHandler.js
server/utils/nunjucksSetup.js
server/views/case-list.njk
server/views/outcomes/casesInProgress.njk
server/views/outcomes/casesToResult.njk
server/views/outcomes/resultedCases.njk
server/views/partials/layout.njk

Filter fixed and into main. ready to proceed.

feat: PIC-3607 Outcome mass action (assign to)

---

server/routes/handlers/caseSummary.js
server/routes/handlers/index.js

Added service call to post handler

Fix: Call Api from case summary post handler

---

helm_deploy/values-prod.yaml

Update IP Allow to match new MOJO ip's

PIC-3913: Add additional ip ranges

---

integration-tests/cypress/e2e/case-progress.feature
integration-tests/cypress/e2e/case-progress/steps.js
server/views/components/hearing-notes/template.njk

JIRA Link : https://dsdmoj.atlassian.net/browse/PIC-3137

PIC-3137: Add note label becomes Enter a note

---

server/routes/handlers/getAddHearingOutcomeHandler.js

New tracking event to help count number of cases added to the hearing outcome workflow

Feat: Add event for AddHearingOutcome

---

server/views/components/hearing-notes/template.njk

JIRA link : https://dsdmoj.atlassian.net/browse/PIC-4043

PIC-4043: Disambiguate save buttons for hearing notes.

---

integration-tests/cypress/e2e/matching.feature
server/config.js
server/routes/handlers/getMatchingRecordRouteHandler.js
server/routes/helpers.js
server/services/case-service.js
server/views/match-defendant.njk
tests/routes/handlers/getMatchingRecordRouteHandler.test.js
tests/routes/view.test.js
tests/services/case-service.test.js

JIRA Link : https://dsdmoj.atlassian.net/browse/PIC-4268

Pic 4268 showing all possible records text

---

server/routes/handlers/catchAsyncErrors.js
server/routes/index.js
server/services/case-service.js
tests/routes/view.test.js
tests/services/case-service.test.js

Changes for investigation : https://dsdmoj.atlassian.net/browse/PIC-4274

PIC-4274: Adding logs and calling version2 of api for getting case list

---

server/routes/index.js
tests/routes/view.test.js

Pic 4274 fix

---

server/routes/index.js
server/services/case-service.js
tests/routes/view.test.js
tests/services/case-service.test.js

Revery using the paged case list

Pic 4274 revert service change

---

integration-tests/cypress/e2e/matching.feature
integration-tests/cypress/support/step_definitions/button-group.js
server/views/components/button-group/macro.njk
server/views/components/button-group/template.njk
server/views/match-unlink.njk

PIC-3156: Create a component for the GDS standard button input and cancel link along with int test steps.

PIC-3156: Unlink nDelius page button/cancel link alignment

---

integration-tests/cypress/e2e/matching.feature
server/config.js
server/routes/handlers/matchRecords/matchingRecordRouteHandler.js
server/routes/helpers.js
server/services/case-service.js
server/views/match-defendant.njk
tests/routes/handlers/matchRecords/matchingRecordRouteHandler.test.js
tests/routes/view.test.js
tests/services/case-service.test.js

https://github.com/user-attachments/assets/2449542b-be28-4bcb-a30f-c071c16ae698
JIRA Link : https://dsdmoj.atlassian.net/browse/PIC-4268

PIC-4268: Removing link to show all records and matchProbability filter

---

helm_deploy/prepare-a-case/templates/_envs.tpl

💚 Fix build

---

server/utils/features.js

Add KSS courts to enabled courts list.
In preparation for the live roll out to KSS courts on 03/03/25

PIC-5401 Allow KSS courts to use service
